### ISSUE TITLE
Openfire 4.8.0 Incompatable?

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-loadStats-plugin#11]
```
2024.01.12 12:33:17.653 ERROR [PluginMonitorExec-3]: org.jivesoftware.openfire.container.PluginManager - An exception occurred while loading plugin 'loadstats':
java.lang.NoClassDefFoundError: org/apache/mina/transport/socket/SocketAcceptor
	at org.jivesoftware.openfire.plugin.StatisticPlugin.initializePlugin(StatisticPlugin.java:36) ~[loadStats-1.2.1.jar:?]
	at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:637) [xmppserver-4.8.0.jar:4.8.0]
	at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:380) [xmppserver-4.8.0.jar:4.8.0]
	at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:368) [xmppserver-4.8.0.jar:4.8.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.mina.transport.socket.SocketAcceptor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 8 more
```

**Comment by guusdk** [comment]
In Openfire 4.8.0, Apache MINA was removed. That explains why the plugin cannot find MINA's SocketAcceptor. This plugin will need to be modified to account for this.
