### ISSUE TITLE
Plugin version 1.2.0 will not deploy in OpenFire 4.4.4/Linux

### ISSUE THREAD

**Issue by tantrum-junkie** [igniterealtime/openfire-loadStats-plugin#2]
Other sources were suggesting that the camel case name "loadStats" is a problem.
The expanded plugin directory is named "loadstats".

Would be nice if this could be fixed or you could give any pointers what the problem is.
I'll also be happy to try to fix it myself then.

The logged exception after deployment is
```
2020.02.05 16:18:49 WARN  [pool-6-thread-1]: org.jivesoftware.openfire.container.PluginMonitor - Detected plugin duplicates for name: 'loadstats'. Only one plugin will be loaded.
2020.02.05 16:18:49 ERROR [pool-516-thread-1]: org.jivesoftware.openfire.container.PluginManager - An exception occurred while loading plugin 'loadstats':
java.lang.ClassNotFoundException: org.jivesoftware.openfire.plugin.StatisticPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
        at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:585) [xmppserver-4.4.4.jar:4.4.4]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:374) [xmppserver-4.4.4.jar:4.4.4]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:362) [xmppserver-4.4.4.jar:4.4.4]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

```

**Comment by akrherz** [comment]
sorry that nobody responded to you, I just released 1.2.1, does it fail for you?  On 4.6.2, I got a strange error:

```
2021.02.19 10:21:06 INFO  [Jetty-QTP-AdminConsole-15296]: org.directwebremoting.log.startup - Starting: DwrServlet v3.0.3-dev on jetty/9.4.35.v20201120 / JDK 1.8.0_282 from Red Hat, Inc. at 
2021.02.19 10:21:06 INFO  [Jetty-QTP-AdminConsole-15296]: org.directwebremoting.log.startup - Starting: Using container abstraction org.directwebremoting.server.servlet3.Servlet30ContainerAbstraction
2021.02.19 10:21:08 ERROR [Jetty-QTP-AdminConsole-68310]: org.jivesoftware.openfire.container.PluginManager - Error installing plugin: pluginFilename was null or empty.
2021.02.19 10:21:08 ERROR [Jetty-QTP-AdminConsole-68310]: plugin-admin.jsp - Plugin manager failed to install plugin: 
2021.02.19 10:21:15 INFO  [pool-60798-thread-1]: org.jivesoftware.openfire.container.PluginManager - Successfully loaded plugin 'loadstats'.
2021.02.19 10:21:15 INFO  [pool-6-thread-1]: org.jivesoftware.openfire.container.PluginMonitor - Finished processing all plugins.
```
